[project]
name = "ismf-battery-monitor"
version = "1.0.0-dev.1"
description = "Get \"at-a-glance\" battery status using your Framework 16 LED matrix module!"
authors = [
    {name = "Taylor B.",email = "t.blackstone@inspyre.tech"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "is-matrix-forge (>=1.0.0.dev28)",
    "platformdirs>=4.0.0",
    "psutil>=5.9.0",
    "easy-exit-calls>=1.0.0.dev1",
    "inspyre-toolbox>=0.1.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
is-matrix-forge = {allow-prereleases = true}
platformdirs = ">=4.0.0"
psutil = ">=5.9.0"
easy-exit-calls = ">=1.0.0.dev1"
inspyre-toolbox = ">=0.1.0"

[tool.poetry]
packages = [
    { include = "ismf_battery_monitor" }
]
include = [
    "ismf_battery_monitor/*.json",
    "ismf_battery_monitor/assets/*.json",
]

[tool.poetry.scripts]
"ismf-battery-monitor" = "ismf_battery_monitor.scripts.battery_monitor.main:main"

[tool.poetry.group.dev.dependencies]
ipython = "^9.6.0"
prompt-toolkit = "^3.0.52"
ptipython = "^1.0.1"
pytest = "^8.0.0"

